//
// Created by MAC on 2019/6/19.
//

#ifndef EFS_UTILITY_H
#define EFS_UTILITY_H

#define _BLOCK_SIZE 1024
#define _OS_PART_BLOCK_SIZE 4096
#define _FILENAME_MAXLEN 20
#define _BIOS_BUF_BLOCK_SIZE 1024
#define _FORMAT_BUFFER_SIZE 100

#endif //EFS_UTILITY_H
