//
// Created by MAC on 2019/6/19.
//

#ifndef EFS_UTILITY_H
#define EFS_UTILITY_H

#define BLOCK_SIZE 1024
#define OS_PART_BLOCK_SIZE 4096
#define FILENAME_MAXLEN 20
#define BIOS_BUF_BLOCK_SIZE 1024
#define FORMAT_BUFFER_SIZE 100

#endif //EFS_UTILITY_H
